### ISSUE TITLE
大佬你好，出现如下错误  Unable to find image 'bestwu/qq:office' locally

### ISSUE THREAD

**Issue by Luo-Zhongwei** [ygcaicn/ubuntu_qq#1]
错误如下
lzw@resplendent-star:~$ bash <(curl -L -s https://raw.githubusercontent.com/ygcaicn/ubuntu_qq/master/qq.sh)
remove ~/.local/bin/qq.sh
remove ~/.local/share/icons/hicolor/256x256/apps/WINE_TIM.png
remove ~/.local/share/applications/TIM.desktop
/dev/fd/63: 第 10 行: [: export: 需要二元表达式
Install this script to ~/.local/bin/qq.sh
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  5285  100  5285    0     0   1562      0  0:00:03  0:00:03 --:--:--  1562
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 17039  100 17039    0     0   3133      0  0:00:05  0:00:05 --:--:--  3451
Unable to find image 'bestwu/qq:office' locally
docker: Error response from daemon: Get https://registry-1.docker.io/v2/bestwu/qq/manifests/office: Get https://auth.docker.io/token?scope=repository%3Abestwu%2Fqq%3Apull&service=registry.docker.io: net/http: TLS handshake timeout.
See 'docker run --help'.

**Comment by ygcaicn** [comment]
检测你的网络，尝试
```
docker run hello-world
````

如果还是不行，尝试换国内hub
```
vi /etc/docker/daemon.json

{
  "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn"]
}
```
然后重启docker
```
sudo systemctl daemon-reload
sudo systemctl restart docker
```

**Comment by Luo-Zhongwei** [comment]
大佬您好，
1）能不能给我发一下daemon.json完整的内容，我不小心好像把这个json内容给删了
2）docker run hello-world 得到了这样的结果


Unable to find image 'hello-world:latest' locally docker: Error response from daemon: Get https://registry-1.docker.io/v2/library/hello-world/manifests/latest: net/http: TLS handshake timeout. See 'docker run --help'.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "jachin"<notifications@github.com&gt;; 
发送时间: 2020年3月3日(星期二) 中午1:08
收件人: "ygcaicn/ubuntu_qq"<ubuntu_qq@noreply.github.com&gt;; 
抄送: "485434977"<485434977@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [ygcaicn/ubuntu_qq] 大佬你好，出现如下错误  Unable to find image &#39;bestwu/qq:office&#39; locally (#1)




检测你的网络，尝试
 docker run hello-world  
如果还是不行，尝试换国内hub
 vi /etc/docker/daemon.json {   "registry-mirrors": ["https://docker.mirrors.ustc.edu.cn"] }

**Comment by ygcaicn** [comment]
上面展示的就是daemon.json的全部，目测你的docker安装的有问题，参考https://yeasy.gitbooks.io/docker_practice/install/ubuntu.html
