### ISSUE TITLE
ubuntu19.04 闪退有碰到过么？

### ISSUE THREAD

**Issue by BruceOuyang** [ygcaicn/ubuntu_qq#3]
ubuntu19.04 闪退有碰到过么？

**Comment by ygcaicn** [comment]
碰到过，上游docker镜像出的问题。可以尝试 qq -c 或wechat -c 清理一下再重新启动。

**Comment by BruceOuyang** [comment]
> 碰到过，上游docker镜像出的问题。可以尝试 qq -c 或wechat -c 清理一下再重新启动。

```
qq -c 
wechat -c
```
这两句代码不能直接执行的吧？

**Comment by ygcaicn** [comment]
> > 碰到过，上游docker镜像出的问题。可以尝试 qq -c 或wechat -c 清理一下再重新启动。
> 
> ```
> qq -c 
> wechat -c
> ```
> 
> 这两句代码不能直接执行的吧？

是的，只是清理掉缓存，清理掉再尝试启动。

**Comment by BruceOuyang** [comment]
问题是我应该在哪里执行这句命令呢，终端直接执行 qq -c 会提示 qq 不是可执行命令，docker qq -c也是不对的，麻烦明示一下 @ygcaicn

**Comment by BruceOuyang** [comment]
可能是我本地环境问题导致的
